In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
a = np.linspace(0, 10, 100)

In [7]:
b = a.reshape(10, 10)

In [8]:
a[5:10]

array([ 0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091])

In [10]:
b[4]

array([ 4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495])

In [11]:
b[:,4]

array([ 0.4040404 ,  1.41414141,  2.42424242,  3.43434343,  4.44444444,
        5.45454545,  6.46464646,  7.47474747,  8.48484848,  9.49494949])

In [12]:
b[5, 8]

5.8585858585858581

In [13]:
b.ndim

2

In [14]:
b.shape

(10, 10)

In [15]:
b**2

array([[  0.00000000e+00,   1.02030405e-02,   4.08121620e-02,
          9.18273646e-02,   1.63248648e-01,   2.55076013e-01,
          3.67309458e-01,   4.99948985e-01,   6.52994592e-01,
          8.26446281e-01],
       [  1.02030405e+00,   1.23456790e+00,   1.46923783e+00,
          1.72431385e+00,   1.99979594e+00,   2.29568411e+00,
          2.61197837e+00,   2.94867871e+00,   3.30578512e+00,
          3.68329762e+00],
       [  4.08121620e+00,   4.49954086e+00,   4.93827160e+00,
          5.39740843e+00,   5.87695133e+00,   6.37690032e+00,
          6.89725538e+00,   7.43801653e+00,   7.99918376e+00,
          8.58075707e+00],
       [  9.18273646e+00,   9.80512193e+00,   1.04479135e+01,
          1.11111111e+01,   1.17947148e+01,   1.24987246e+01,
          1.32231405e+01,   1.39679625e+01,   1.47331905e+01,
          1.55188246e+01],
       [  1.63248648e+01,   1.71513111e+01,   1.79981635e+01,
          1.88654219e+01,   1.97530864e+01,   2.06611570e+01,
          2.15896337e+01

In [23]:
I = np.matrix(np.identity(2))

In [24]:
I*I

matrix([[ 1.,  0.],
        [ 0.,  1.]])

In [25]:
R = np.matrix([[1,2],[3,4]])

In [26]:
R

matrix([[1, 2],
        [3, 4]])

In [27]:
R * I

matrix([[ 1.,  2.],
        [ 3.,  4.]])

In [28]:
R**2

matrix([[ 7, 10],
        [15, 22]])

In [29]:
A = np.array(R)

In [30]:
A**2

array([[ 1,  4],
       [ 9, 16]])

In [31]:
np.sqrt(A)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [33]:
np.argmax(a)

99

In [34]:
np.average(A)

2.5

In [37]:
np.bincount(A.flatten())

array([0, 1, 1, 1, 1])

In [38]:
R

matrix([[1, 2],
        [3, 4]])

In [39]:
R.T

matrix([[1, 3],
        [2, 4]])

In [40]:
np.dot(R, R.T)

matrix([[ 5, 11],
        [11, 25]])

In [41]:
np.dot?

In [42]:
np.cross(R, R.T)

array([1, 4])

In [47]:
np.linalg.inv(R) * R

matrix([[  1.00000000e+00,   4.44089210e-16],
        [  0.00000000e+00,   1.00000000e+00]])

In [45]:
np.random.normal(size=100)

array([-1.52265059,  0.82034332, -0.61545142,  0.90411773, -0.93056518,
       -0.51491029, -1.76282503,  2.64138306, -1.5039348 , -0.67218617,
       -1.29988641,  0.71008401, -1.28219558,  0.66610427, -0.51449387,
       -0.91826202,  0.06045518, -0.25604012, -1.27043822,  0.56663678,
       -2.39107164, -0.20265363,  0.31534983, -0.46123283,  0.41951001,
       -0.74828128,  1.17025   ,  0.74925629,  0.5216537 , -0.06307007,
       -0.35136673,  0.3627982 ,  0.27662233, -0.19542072, -0.8180271 ,
        0.35951366,  0.19904169, -0.06732768,  0.35776353,  1.78508892,
        0.36348765, -0.12458157, -1.99246267,  1.31064051,  0.08535573,
        0.78297651,  1.06316859, -0.56666261,  0.60382079, -0.05283306,
        0.52656705,  2.30149517,  0.09603484,  0.48052431,  1.50465938,
       -1.07054533, -0.92822205,  0.50244665,  1.34857681,  1.08351917,
       -1.00059246, -2.05867801,  0.4874101 , -1.33671676, -0.13481961,
        0.96561338,  2.25161194, -0.39934344,  0.96159937, -0.69

In [52]:
np.fft.fft(a, n=5)

array([ 1.01010101+0.j        , -0.25252525+0.34757119j,
       -0.25252525+0.08205043j, -0.25252525-0.08205043j,
       -0.25252525-0.34757119j])

In [55]:
np.fft.fft2(b)

array([[  5.00000000e+02 +0.00000000e+00j,
         -5.05050505e+00 +1.55438562e+01j,
         -5.05050505e+00 +6.95142384e+00j,
         -5.05050505e+00 +3.66940671e+00j,
         -5.05050505e+00 +1.64100857e+00j,
         -5.05050505e+00 +5.55111512e-17j,
         -5.05050505e+00 -1.64100857e+00j,
         -5.05050505e+00 -3.66940671e+00j,
         -5.05050505e+00 -6.95142384e+00j,
         -5.05050505e+00 -1.55438562e+01j],
       [ -5.05050505e+01 +1.55438562e+02j,
         -1.13076654e-15 -6.21033611e-16j,
          2.09190193e-15 +1.21892708e-15j,
         -6.54987120e-16 -7.09044153e-16j,
          4.98791864e-15 +3.71484344e-16j,
          6.00183408e-16 +1.76365598e-16j,
         -5.70647007e-15 +8.19883561e-15j,
         -2.46203822e-15 +7.60779451e-16j,
          3.63176131e-15 -5.73627690e-16j,
          8.41488779e-16 -1.87708519e-16j],
       [ -5.05050505e+01 +6.95142384e+01j,
         -1.16645672e-15 -5.15676603e-16j,
         -2.45714931e-15 +2.96563730e-15j,
         